In [1]:
import pandas as pd

In [2]:
import openpyxl

In [3]:

import pandas as pd

# Load the Kolkata cars Excel file
df_kolkata = pd.read_excel('C:/Users/DELL/Desktop/cars3/kolkata_cars.xlsx')
df_kolkata['city'] = 'Kolkata'

# Display the first few rows
print(df_kolkata.head())

                                      new_car_detail  \
0  {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
1  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
2  {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
3  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
4  {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...

                                    new_car_overview  \
0  {'heading': 'Car overview', 'top': [{'key': 'R...
1  {'heading': 'Car overview', 'top': [{'key': 'R...
2  {'heading': 'Car overview', 'top': [{'key': 'R...
3  {'heading': 'Car overview', 'top': [{'key': 'R...
4  {'heading': 'Car overview', 'top': [{'key': 'R...

                                     new_car_feature  \
0  {'heading': 'Features', 'top': [{'value': 'Pow...
1  {'heading': 'Features', 'top': [{'value': 'Pow...
2  {'heading': 'Features', 'top': [{'value': 'Pow...
3  {'heading': 'Features', 'top': [{'value': 'Pow...
4  {'heading': 'Features', 'top': [{'value': 'Pow...

                                       new_car_specs  \
0  {'heading': 'Specifications', 'top': [{'key': ...
1  {'heading': 'Specifications', 'top': [{'key': ...
2  {'heading': 'Specifications', 'top': [{'key': ...
3  {'heading': 'Specifications', 'top': [{'key': ...
4  {'heading': 'Specifications', 'top': [{'key': ...

                                           car_links     city
0  https://www.cardekho.com/used-car-details/used...  Kolkata
1  https://www.cardekho.com/buy-used-car-details/...  Kolkata
2  https://www.cardekho.com/used-car-details/used...  Kolkata
3  https://www.cardekho.com/buy-used-car-details/...  Kolkata
4  https://www.cardekho.com/used-car-details/used...  Kolkata

In [10]:

import pandas as pd

# Load the Kolkata cars Excel file
df_chennai = pd.read_excel('C:/Users/DELL/Desktop/cars3/chennai_cars.xlsx')
df_chennai['city'] = 'Chennai'

# Display the first few rows
print(df_chennai.head(1))

                                      new_car_detail  \
0  {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...

                                    new_car_overview  \
0  {'heading': 'Car overview', 'top': [{'key': 'R...

                                     new_car_feature  \
0  {'heading': 'Features', 'top': [{'value': 'Pow...

                                       new_car_specs  \
0  {'heading': 'Specifications', 'top': [{'key': ...

                                           car_links     city
0  https://www.cardekho.com/used-car-details/used...  Chennai

In [5]:
import pandas as pd

# Load the Kolkata cars Excel file
df_delhi = pd.read_excel('C:/Users/DELL/Desktop/cars3/delhi_cars.xlsx')
df_delhi['city'] = 'Delhi'
# Display the first few rows
print(df_delhi.head())

                                      new_car_detail  \
0  {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1  {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
2  {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
3  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
4  {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...

                                    new_car_overview  \
0  {'heading': 'Car overview', 'top': [{'key': 'R...
1  {'heading': 'Car overview', 'top': [{'key': 'R...
2  {'heading': 'Car overview', 'top': [{'key': 'R...
3  {'heading': 'Car overview', 'top': [{'key': 'R...
4  {'heading': 'Car overview', 'top': [{'key': 'R...

                                     new_car_feature  \
0  {'heading': 'Features', 'top': [{'value': 'Pow...
1  {'heading': 'Features', 'top': [{'value': 'Pow...
2  {'heading': 'Features', 'top': [{'value': 'Pow...
3  {'heading': 'Features', 'top': [{'value': 'Pow...
4  {'heading': 'Features', 'top': [{'value': 'Pow...

                                       new_car_specs  \
0  {'heading': 'Specifications', 'top': [{'key': ...
1  {'heading': 'Specifications', 'top': [{'key': ...
2  {'heading': 'Specifications', 'top': [{'key': ...
3  {'heading': 'Specifications', 'top': [{'key': ...
4  {'heading': 'Specifications', 'top': [{'key': ...

                                           car_links   city
0  https://www.cardekho.com/used-car-details/used...  Delhi
1  https://www.cardekho.com/buy-used-car-details/...  Delhi
2  https://www.cardekho.com/used-car-details/used...  Delhi
3  https://www.cardekho.com/buy-used-car-details/...  Delhi
4  https://www.cardekho.com/used-car-details/used...  Delhi

In [6]:
import pandas as pd

# Load the Kolkata cars Excel file
df_hyderabad = pd.read_excel('C:/Users/DELL/Desktop/cars3/hyderabad_cars.xlsx')
df_hyderabad['city'] = 'Hyderabad'
# Display the first few rows
print(df_hyderabad.head())

                                      new_car_detail  \
0  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
2  {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
3  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
4  {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...

                                    new_car_overview  \
0  {'heading': 'Car overview', 'top': [{'key': 'R...
1  {'heading': 'Car overview', 'top': [{'key': 'R...
2  {'heading': 'Car overview', 'top': [{'key': 'R...
3  {'heading': 'Car overview', 'top': [{'key': 'R...
4  {'heading': 'Car overview', 'top': [{'key': 'R...

                                     new_car_feature  \
0  {'heading': 'Features', 'top': [{'value': 'Pow...
1  {'heading': 'Features', 'top': [{'value': 'Pow...
2  {'heading': 'Features', 'top': [{'value': 'Pow...
3  {'heading': 'Features', 'top': [{'value': 'Pow...
4  {'heading': 'Features', 'top': [{'value': 'Pow...

                                       new_car_specs  \
0  {'heading': 'Specifications', 'top': [{'key': ...
1  {'heading': 'Specifications', 'top': [{'key': ...
2  {'heading': 'Specifications', 'top': [{'key': ...
3  {'heading': 'Specifications', 'top': [{'key': ...
4  {'heading': 'Specifications', 'top': [{'key': ...

                                           car_links       city
0  https://www.cardekho.com/used-car-details/used...  Hyderabad
1  https://www.cardekho.com/buy-used-car-details/...  Hyderabad
2  https://www.cardekho.com/used-car-details/used...  Hyderabad
3  https://www.cardekho.com/buy-used-car-details/...  Hyderabad
4  https://www.cardekho.com/used-car-details/used...  Hyderabad

In [7]:

import pandas as pd

# Load the Kolkata cars Excel file
df_jaipur = pd.read_excel('C:/Users/DELL/Desktop/cars3/jaipur_cars.xlsx')
df_jaipur['city'] = 'Jaipur'

# Display the first few rows
print(df_jaipur.head())

                                      new_car_detail  \
0  {'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...
1  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
2  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
3  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
4  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...

                                    new_car_overview  \
0  {'heading': 'Car overview', 'top': [{'key': 'R...
1  {'heading': 'Car overview', 'top': [{'key': 'R...
2  {'heading': 'Car overview', 'top': [{'key': 'R...
3  {'heading': 'Car overview', 'top': [{'key': 'R...
4  {'heading': 'Car overview', 'top': [{'key': 'R...

                                     new_car_feature  \
0  {'heading': 'Features', 'top': [{'value': 'Pow...
1  {'heading': 'Features', 'top': [{'value': 'Pow...
2  {'heading': 'Features', 'top': [{'value': 'Pow...
3  {'heading': 'Features', 'top': [{'value': 'Pow...
4  {'heading': 'Features', 'top': [{'value': 'Pow...

                                       new_car_specs  \
0  {'heading': 'Specifications', 'top': [{'key': ...
1  {'heading': 'Specifications', 'top': [{'key': ...
2  {'heading': 'Specifications', 'top': [{'key': ...
3  {'heading': 'Specifications', 'top': [{'key': ...
4  {'heading': 'Specifications', 'top': [{'key': ...

                                           car_links    city
0  https://www.cardekho.com/used-car-details/used...  Jaipur
1  https://www.cardekho.com/buy-used-car-details/...  Jaipur
2  https://www.cardekho.com/used-car-details/used...  Jaipur
3  https://www.cardekho.com/buy-used-car-details/...  Jaipur
4  https://www.cardekho.com/used-car-details/used...  Jaipur

In [8]:
import pandas as pd

# Load the Kolkata cars Excel file
df_bangalore = pd.read_excel('C:/Users/DELL/Desktop/cars3/bangalore_cars.xlsx')
df_bangalore['city'] = 'Bangalore'

# Display the first few rows
print(df_bangalore.head())

                                      new_car_detail  \
0  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1  {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
2  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
3  {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
4  {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...

                                    new_car_overview  \
0  {'heading': 'Car overview', 'top': [{'key': 'R...
1  {'heading': 'Car overview', 'top': [{'key': 'R...
2  {'heading': 'Car overview', 'top': [{'key': 'R...
3  {'heading': 'Car overview', 'top': [{'key': 'R...
4  {'heading': 'Car overview', 'top': [{'key': 'R...

                                     new_car_feature  \
0  {'heading': 'Features', 'top': [{'value': 'Pow...
1  {'heading': 'Features', 'top': [{'value': 'Pow...
2  {'heading': 'Features', 'top': [{'value': 'Pow...
3  {'heading': 'Features', 'top': [{'value': 'Pow...
4  {'heading': 'Features', 'top': [{'value': 'Pow...

                                       new_car_specs  \
0  {'heading': 'Specifications', 'top': [{'key': ...
1  {'heading': 'Specifications', 'top': [{'key': ...
2  {'heading': 'Specifications', 'top': [{'key': ...
3  {'heading': 'Specifications', 'top': [{'key': ...
4  {'heading': 'Specifications', 'top': [{'key': ...

                                           car_links       city
0  https://www.cardekho.com/used-car-details/used...  Bangalore
1  https://www.cardekho.com/buy-used-car-details/...  Bangalore
2  https://www.cardekho.com/used-car-details/used...  Bangalore
3  https://www.cardekho.com/buy-used-car-details/...  Bangalore
4  https://www.cardekho.com/used-car-details/used...  Bangalore

In [14]:
import pandas as pd

# Assuming df_kolkata, df_chennai, df_delhi, df_hyderabad, df_jaipur, df_bangalore are your DataFrames

# Concatenate all DataFrames
df_combined = pd.concat([df_kolkata, df_chennai, df_delhi, df_hyderabad, df_jaipur, df_bangalore], axis=0).reset_index(drop=True)

# Display the combined DataFrame
df_combined.head(1)

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links,city
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata

In [13]:
df_combined=df_combined.drop(['car_links'],axis=1)

In [15]:
import ast

df_combined['new_car_detail'] = df_combined['new_car_detail'].apply(ast.literal_eval)
df_combined['new_car_overview'] = df_combined['new_car_overview'].apply(ast.literal_eval)
df_combined['new_car_feature'] = df_combined['new_car_feature'].apply(ast.literal_eval)
df_combined['new_car_specs'] = df_combined['new_car_specs'].apply(ast.literal_eval)

In [16]:
df_combined

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links,city
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Kolkata
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Kolkata
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
...,...,...,...,...,...,...
8364,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore
8365,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore
8366,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore
8367,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore
8368,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore

In [17]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt

In [18]:
import pandas as pd

# Normalize the 'new_car_detail' column
new_car = pd.json_normalize(df_combined['new_car_detail'])

# Display the first row of the new_car DataFrame
new_car.head(1)

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Petrol,Sedan,"70,000",Automatic,3,3rd Owner,Toyota,Toyota Camry,2014,2123,Hybrid,₹ 9.75 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

In [19]:
df_combined['new_car_detail'][0]

{'it': 0,
 'ft': 'Petrol',
 'bt': 'Sedan',
 'km': '70,000',
 'transmission': 'Automatic',
 'ownerNo': 3,
 'owner': '3rd Owner',
 'oem': 'Toyota',
 'model': 'Toyota Camry',
 'modelYear': 2014,
 'centralVariantId': 2123,
 'variantName': 'Hybrid',
 'price': '₹ 9.75 Lakh',
 'priceActual': '',
 'priceSaving': '',
 'priceFixedText': None,
 'trendingText': {'imgUrl': 'https://stimg.cardekho.com/used-cars/common/icons/trending.svg',
  'heading': 'Trending Car!',
  'desc': 'High chances of sale in next 6 days'}}

In [20]:
def row_find(row):
    row_info={item['key']:item['value'] for item in row ['top']}
    return row_info
view_unpack=df_combined['new_car_overview'].apply(lambda row:pd.Series(row_find(row)))
view_unpack.head(1)

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture
0,2014,Third Party insurance,Petrol,5 Seats,"70,000 Kms",WB02,Third Owner,2494 cc,Automatic,2014.0

In [21]:
df_combined['new_car_overview'][0]

{'heading': 'Car overview',
 'top': [{'key': 'Registration Year',
   'value': '2014',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/registrationYear.svg'},
  {'key': 'Insurance Validity',
   'value': 'Third Party insurance',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/insuranceValidity.svg'},
  {'key': 'Fuel Type',
   'value': 'Petrol',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/fuel.svg'},
  {'key': 'Seats',
   'value': '5 Seats',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/seats.svg'},
  {'key': 'Kms Driven',
   'value': '70,000 Kms',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/kmsDriven.svg'},
  {'key': 'RTO',
   'value': 'WB02',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/rto.svg'},
  {'key': 'Ownership',
   'value': 'Third Owner',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/ownership.svg'},
  {'key': 'Engine Displacement',
   'value': '2494 cc',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/engineDisplacement.svg'},
  {'key': 'Transmission',
   'value': 'Automatic',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/transmission.svg'},
  {'key': 'Year of Manufacture',
   'value': 2014,
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/yearManufacture.svg'}],
 'bottomData': None}

In [22]:
def p_features(row):
    features = {}

    # Flatten 'top' values
    for item in row['top']:
        features[item['value']] = True
    
    # Flatten 'data' values
    for data_item in row.get('data', []):
        for sub_item in data_item.get('list', []):
            features[sub_item['value']] = True
    
    return features

features_unpack= df_combined['new_car_feature'].apply(lambda row: pd.Series(p_features(row)))

features_unpack.head(1)

,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Cd Player,Power Windows Rear,...,Remote Horn Light Control,Dual Tone Body Colour,Compass,Lane Watch Camera,Active Noise Cancellation,Smart Key Band,Headlamp Washers,Real Time Vehicle Tracking,Cassette Player,Power Folding3rd Row Seat
0,True,True,True,True,True,True,True,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df_combined['new_car_feature'][0]

{'heading': 'Features',
 'top': [{'value': 'Power Steering'},
  {'value': 'Power Windows Front'},
  {'value': 'Air Conditioner'},
  {'value': 'Heater'},
  {'value': 'Adjustable Head Lights'},
  {'value': 'Fog Lights Front'},
  {'value': 'Anti Lock Braking System'},
  {'value': 'Brake Assist'},
  {'value': 'Cd Player'}],
 'data': [{'heading': 'Comfort & Convenience',
   'subHeading': 'Comfort',
   'list': [{'value': 'Power Steering'},
    {'value': 'Power Windows Front'},
    {'value': 'Power Windows Rear'},
    {'value': 'Air Quality Control'},
    {'value': 'Remote Trunk Opener'},
    {'value': 'Low Fuel Warning Light'},
    {'value': 'Accessory Power Outlet'},
    {'value': 'Trunk Light'},
    {'value': 'Vanity Mirror'},
    {'value': 'Rear Seat Headrest'},
    {'value': 'Rear Seat Centre Arm Rest'},
    {'value': 'Cup Holders Front'},
    {'value': 'Cup Holders Rear'},
    {'value': 'Seat Lumbar Support'},
    {'value': 'Multifunction Steering Wheel'},
    {'value': 'Rear ACVents'}]},
  {'heading': 'Interior',
   'subHeading': 'Interior',
   'list': [{'value': 'Air Conditioner'},
    {'value': 'Heater'},
    {'value': 'Adjustable Steering'},
    {'value': 'Digital Odometer'},
    {'value': 'Tachometer'},
    {'value': 'Electronic Multi Tripmeter'},
    {'value': 'Leather Seats'},
    {'value': 'Leather Steering Wheel'},
    {'value': 'Glove Compartment'},
    {'value': 'Digital Clock'}]},
  {'heading': 'Exterior',
   'subHeading': 'Exterior',
   'list': [{'value': 'Adjustable Head Lights'},
    {'value': 'Fog Lights Front'},
    {'value': 'Fog Lights Rear'},
    {'value': 'Power Adjustable Exterior Rear View Mirror'},
    {'value': 'Electric Folding Rear View Mirror'},
    {'value': 'Rain Sensing Wiper'},
    {'value': 'Rear Window Defogger'},
    {'value': 'Alloy Wheels'},
    {'value': 'Integrated Antenna'},
    {'value': 'Outside Rear View Mirror Turn Indicators'}]},
  {'heading': 'Safety',
   'subHeading': 'Safety',
   'list': [{'value': 'Anti Lock Braking System'},
    {'value': 'Brake Assist'},
    {'value': 'Centeral Locking'},
    {'value': 'Power Door Locks'},
    {'value': 'Child Safety Locks'},
    {'value': 'Anti Theft Alarm'},
    {'value': 'Driver Air Bag'},
    {'value': 'Passenger Air Bag'},
    {'value': 'Side Air Bag Front'},
    {'value': 'Day Night Rear View Mirror'},
    {'value': 'Passenger Side Rear View Mirror'},
    {'value': 'Halogen Headlamps'},
    {'value': 'Rear Seat Belts'},
    {'value': 'Seat Belt Warning'},
    {'value': 'Door Ajar Warning'},
    {'value': 'Side Impact Beams'},
    {'value': 'Front Impact Beams'},
    {'value': 'Vehicle Stability Control System'},
    {'value': 'Traction Control'},
    {'value': 'Adjustable Seats'},
    {'value': 'Keyless Entry'},
    {'value': 'Centrally Mounted Fuel Tank'},
    {'value': 'Engine Immobilizer'},
    {'value': 'Crash Sensor'},
    {'value': 'Ebd'},
    {'value': 'Anti Theft Device'}]},
  {'heading': 'Entertainment & Communication',
   'subHeading': 'Entertainment',
   'list': [{'value': 'Cd Player'},
    {'value': 'Dvd Player'},
    {'value': 'Radio'},
    {'value': 'Speakers Front'},
    {'value': 'Speakers Rear'}]}],
 'commonIcon': 'https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg'}

In [24]:
import pandas as pd

def find_carspecs(row):
    spec = {}
    
    # Extract specifications from 'top' key
    for item in row.get('top', []):
        key = item.get('key')
        value = item.get('value')
        if key and value:  # Check if key and value are not None
            spec[key] = value
    
    # Extract specifications from nested 'data' key
    for data_item in row.get('data', []):
        for sub_item in data_item.get('list', []):
            key = sub_item.get('key')
            value = sub_item.get('value')
            if key and value:
                spec[key] = value

    return spec

# Apply the modified function and expand the dictionary into separate columns
spec_unpack = df_combined['new_car_specs'].apply(lambda row: pd.Series(find_carspecs(row)))

# Display the first row to check if the specs have been unpacked correctly
print(spec_unpack.head(1))

      Mileage   Engine         Max Power Torque Wheel Size Seats  Color  \
0  19.16 kmpl  2494 CC  158.2bhp@5700rpm  213Nm         17     5  White

              Engine Type Displacement     Max Torque  ...  Front Brake Type  \
0  2AR FXE Petrol Engine          2494  213Nm@4500rpm  ...   Ventilated Disc

   Rear Brake Type        Tyre Type Alloy Wheel Size No Door Numbers  \
0       Solid Disc  Tubeless,Radial               17               4

  Ground Clearance Unladen Cargo Volumn Compression Ratio Acceleration  \
0                      NaN          NaN               NaN          NaN

  Top Speed
0       NaN

[1 rows x 40 columns]

In [25]:
df_combined['new_car_specs'][0]

{'heading': 'Specifications',
 'top': [{'key': 'Mileage', 'value': '19.16 kmpl'},
  {'key': 'Engine', 'value': '2494 CC'},
  {'key': 'Max Power', 'value': '158.2bhp'},
  {'key': 'Torque', 'value': '213Nm'},
  {'key': 'Wheel Size', 'value': '17'},
  {'key': 'Seats', 'value': '5'}],
 'data': [{'heading': 'Engine and Transmission',
   'subHeading': 'Engine',
   'list': [{'key': 'Color', 'value': 'White'},
    {'key': 'Engine Type', 'value': '2AR FXE Petrol Engine '},
    {'key': 'Displacement', 'value': '2494'},
    {'key': 'Max Power', 'value': '158.2bhp@5700rpm'},
    {'key': 'Max Torque', 'value': '213Nm@4500rpm'},
    {'key': 'No of Cylinder', 'value': 4},
    {'key': 'Values per Cylinder', 'value': 4},
    {'key': 'Value Configuration', 'value': 'DOHC'},
    {'key': 'Fuel Suppy System', 'value': 'Electronic Fuel Injection(EFI)'},
    {'key': 'BoreX Stroke', 'value': '90 X 98 mm'},
    {'key': 'Turbo Charger', 'value': 'No'},
    {'key': 'Super Charger', 'value': 'No'}]},
  {'heading': 'Dimensions & Capacity',
   'subHeading': 'Dimensions',
   'list': [{'key': 'Length', 'value': '4825mm'},
    {'key': 'Width', 'value': '1825mm'},
    {'key': 'Height', 'value': '1480mm'},
    {'key': 'Wheel Base', 'value': '2775mm'},
    {'key': 'Front Tread', 'value': '1580mm'},
    {'key': 'Rear Tread', 'value': '1570mm'},
    {'key': 'Kerb Weight', 'value': '1625kg'},
    {'key': 'Gross Weight', 'value': '2100kg'}]},
  {'heading': 'Miscellaneous',
   'subHeading': 'Miscellaneous',
   'list': [{'key': 'Gear Box', 'value': '6 Speed '},
    {'key': 'Drive Type', 'value': 'FWD'},
    {'key': 'Seating Capacity', 'value': '5'},
    {'key': 'Steering Type', 'value': 'Power'},
    {'key': 'Turning Radius', 'value': '5.5 metres'},
    {'key': 'Front Brake Type', 'value': 'Ventilated Disc'},
    {'key': 'Rear Brake Type', 'value': 'Solid Disc'},
    {'key': 'Tyre Type', 'value': 'Tubeless,Radial'},
    {'key': 'Alloy Wheel Size', 'value': '17'},
    {'key': 'No Door Numbers', 'value': '4'}]}],
 'commonIcon': ''}

In [26]:
print(new_car.shape, view_unpack.shape, features_unpack.shape, spec_unpack.shape, df_combined.shape)

(8369, 19) (8369, 10) (8369, 173) (8369, 40) (8369, 6)

In [27]:
combined_unpack = pd.concat([new_car, view_unpack, features_unpack, spec_unpack, df_combined['city']], axis=1)

In [29]:
combined_unpack.to_csv('combined_unpack_df.csv', index=False)

In [30]:
df=combined_unpack.to_csv("C:/Users/DELL/Downloads/combined_unpack_df.csv")